### PR TITLE
Update org-mw-footnote-section to new Org

### PR DESCRIPTION
**Pull request by manuel-uberti**
Fix https://github.com/tomalexander/orgmode-mediawiki/issues/13

### CODE REVIEW

**Comment by purcell** [comment]
Hey @tomalexander - it'd be great if you could click merge on this so we don't have to start building MELPA packages of this handy library from somebody else's fork. :-)

**Comment by tomalexander** [comment]
Ah yep, sorry about that.

**Comment by manuel-uberti** [comment]
Thank you, we can forget about my fork then. ;-)

**Comment by tomalexander** [comment]
If you'd like to take over ownership of the project then you are welcome to it. My work switched over to confluence so I sadly currently don't have any use for org-mode to mediawiki exporting. Just let me know and we can figure out how to do that.

**Comment by manuel-uberti** [comment]
My Elisp is not good enough, otherwise I'd be happy to step in and help. I just created this PR following the suggestion on https://github.com/tomalexander/orgmode-mediawiki/issues/13.

**Comment by tomalexander** [comment]
ah ok, well thanks for the patch!

**Comment by purcell** [comment]
Thanks Tom.

**Pull request merged**
